import './js/spinner';
import './sass/main.scss';
// import './js/modalFilmCard.js';
import './js/modalFilmCard_V2';
import './js/cardFetc.js';
import './js/teamLightbox';
import './js/pagination.js';
//import './js/registrationModal';
// import '../node_modules/basiclightbox/dist/basicLightbox.min.css';
import './js/keyWordSearch';
import 'regenerator-runtime/runtime.js';
import './js/trailers';
import './js/btn-upp';
import './js/slider';
